[general]
import = [
    "~/.config/alacritty/theme.toml"
]
[font]
size = 12.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[window]
padding = { x = 10, y = 10 }
